import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :fueltruck, FueltruckWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Fueltruck is a trusted-LAN tool served over plain HTTP by default, so SSL is not
# forced. If you front it with a TLS-terminating proxy, build with FORCE_SSL=true to
# enable HTTP→HTTPS redirects + HSTS. Note `:force_ssl` must be set at compile time.
if System.get_env("FORCE_SSL", "false") == "true" do
  config :fueltruck, FueltruckWeb.Endpoint,
    force_ssl: [
      rewrite_on: [:x_forwarded_proto],
      exclude: [hosts: ["localhost", "127.0.0.1"]]
    ]
end

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
